### PR TITLE
 🏃 Generate junit in CI

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
This makes a test run with failing tests pass https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/1053/pull-controller-runtime-test-master/1284892162755923969 ?

**Comment by alvaroaleman** [comment]
@vincepri I've updated the test script to check in CI if the junit xmls have failures as a workaround to the ginkgo not properly failing on failures ¯\_(ツ)_/¯

**Comment by vincepri** [comment]
Any reason we're skipping 30 tests?

**Comment by vincepri** [comment]
Looking at the code, I see the warning on the reporter, I'm hoping that folks don't use this blindly :/

**Comment by alvaroaleman** [comment]
> Any reason we're skipping 30 tests?

No idea but not because of this PR, we just see that now which I guess is a good thing.

> Looking at the code, I see the warning on the reporter, I'm hoping that folks don't use this blindly :/

Yeah, me too :grimacing:

**Comment by alvaroaleman** [comment]
@vincepri are you comfortable with how the change looks like currently?

My subjective impression is that our tests are still flaking quite a bit and it would be great if we could use testgrid to see which tests exactly are flaking how much rather than just seeing "some runs pass, some fail"

**Comment by vincepri** [comment]
Yeah that makes sense, let's get this merged!

/lgtm

**Pull request merged**
