### PR TITLE
:bug: honor LeaderElectionReleaseOnCancel

### PR DESCRIPTION
**Pull request by laverite**
Manager option `LeaderElectionReleaseOnCancel` (added in https://github.com/kubernetes-sigs/controller-runtime/commit/93e6db8d5f04222e42accaa91af027e8bc4ec52b) does not take effect when set. It appears this option is simply not plumbed through all the way to the internal controllerManager.  This PR plumbs the `LeaderElectionReleaseOnCancel` option through so that it is honored.

Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/1522

### CODE REVIEW

**Comment by laverite** [comment]
CLA signed

**Review by alvaroaleman — APPROVED** [review]
thanks!

**Pull request merged**
