### PR TITLE
Updating to k8s 1.11.

### PR DESCRIPTION
**Pull request by n3wscott**
Some things changed between 1.10 to 1.11:

- apimachinery removed pkg/types/NewNamespacedNameFromString
- using mapping.Resource now requires mapping.Resource.String()
- GetAPIGroupResources was moved from discovery to restmapper
- discovery.NewRESTMapper moved to restmapper.NewDiscoveryRESTMapper

### CODE REVIEW

**Comment by n3wscott** [comment]
Not sure what you folks run to trim the source to fix the error. Let me know and I can update.

**Comment by DirectXMan12** [comment]
Yeah, sorry about that.  The error message is *terrible*.  Run `goimports -w path/to/the/file` to autofix the issues.

**Comment by n3wscott** [comment]
I am not able to run the unit tests locally on a mac.

**Comment by n3wscott** [comment]
> I am not able to run the unit tests locally on a mac.

I had to install kubebuilder.

**Comment by DirectXMan12** [comment]
oh?  What problem did you encounter?

**Comment by grantr** [comment]
> I had to install kubebuilder under /usr/local/kubebuilder.

I ran into the same thing in #90.

**Comment by DirectXMan12** [comment]
We're going to have to (temporarily) revert this due to the way kubebuilder currently deals with deps.  We're going to start the whole update process and make sure we have it documented in the future to avoid mishaps.

**Comment by n3wscott** [comment]
No problem, any way to reopen the or or do I have to?

**Pull request merged**
