### PR TITLE
:sparkles: Event broadcast opts

### PR DESCRIPTION
**Pull request by liztio**
New method to set correlator options for event recording
Unverified

### CODE REVIEW

**Comment by liztio** [comment]
I don't think I fully understand the implications of bumping client-go, is that likely to break other things?

**Comment by detiber** [comment]
/assign @DirectXMan12 @fanzhangio 

This issue is affecting us in cluster-api where the Spam Filter is eating events we are generating.

**Comment by DirectXMan12** [comment]
> implications of bumping client-go

Yeah, this needs to be done carefully otherwise we accidentally break backwards compat

**Comment by DirectXMan12** [comment]
besides the aforementioned bump issues (might just pull that in in #588 anyway), this needs at least one of

- good docs
- a sane wrapper

Alternatively, maybe we should just bump this up a level and let you set the recorder-provider directly?

**Comment by DirectXMan12** [comment]
That way we don't need to carry a rather niche dependency on some highly-implementation-specific options

**Comment by liztio** [comment]
> Alternatively, maybe we should just bump this up a level and let you set the recorder-provider directly?

that makes sense to me, let me mock up a PR rq

**Comment by liztio** [comment]
@DirectXMan12 does #591 look any better to you?

**Comment by DirectXMan12** [comment]
yeah, let's switch to that one

**Pull request closed without merging**
