### PR TITLE
:sparkles: [release-0.8] Add client.StrategicMergeFrom

### PR DESCRIPTION
**Pull request by timebertt**
Cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/1406:

This PR adds `client.StrategicMergeFrom`.
The function is similar to `client.{MergeFrom,MergeFromWithOptions}`, but it creates a `strategic-merge-patch` instead of a `merge-patch`. See doc strings for more details about the differences of the two patch types and to figure out when to use which one.

Note, that strategic merge patches are [not supported by CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility).

### CODE REVIEW

**Comment by timebertt** [comment]
I wasn't sure, if we can backport this feature to `0.8`, so I'm kindly asking if it's reasonable by opening this PR.
/assign @alvaroaleman

**Review by alvaroaleman — APPROVED** [review]
/lgtm
/approve

**Comment by timebertt** [comment]
Great, thank you!

**Pull request merged**
