### PR TITLE
[release-0.18] ✨ setup-envtest: download binaries from controller-tools releases

### PR DESCRIPTION
**Pull request by sbueringer**
Manual cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/2811

Notable difference:
* --use-deprecated-gcs defaults to true (see the last commit on this PR)

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold

in case @vincepri wants to have a look

**Comment by damdo** [comment]
@sbueringer could we backport this further back into older release branches?
e.g. release-0.17 / 0.16 and maybe even 0.15 too? (it doesn't have to be an actual release).

We import setup-envtest as a pkg under `/hack/tools` and CR 0.18 enforces go 1.22, 0.17 does the same with 1.21, and we can't have that if we backport this to older releases.

Thanks!

**Comment by sbueringer** [comment]
@damdo can you open cherry-pick PRs?

**Comment by damdo** [comment]
Yes. Opened release-0.17, if happy with the approach I'll open others https://github.com/kubernetes-sigs/controller-runtime/pull/2843

**Comment by sbueringer** [comment]
Sounds good

**Pull request merged**
