### PR TITLE
:sparkles: Add controllerutil.ServerSideApply utility function

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

Related to #347

### CODE REVIEW

**Comment by vincepri** [comment]
@alvaroaleman What do you think about merging this? I don't have any immediate use, but if others find it useful, happy to get it merged and iterate on it later

**Comment by alvaroaleman** [comment]
Not sure, from what it sounded like in the last meeting, SSA usage from go is still very much WIP

**Comment by vincepri** [comment]
Let's close this then!

/close

**Pull request closed without merging**
