### PR TITLE
📖 Fix a small typo

### PR DESCRIPTION
**Pull request by hs0210**
Fix a small typo in the comment: wether --> whether

Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by varshaprasad96** [comment]
/lgtm
@hs0210 can you please include a short description in the PR for CI to pass.

**Comment by hs0210** [comment]
@varshaprasad96 Thanks! Done. PTAL.

**Review by camilamacedo86 — APPROVED** [review]
/approved

**Pull request merged**
