### PR TITLE
:seedling: Update json-patch to v4.9.0

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

/assign @alvaroaleman 
/milestone v0.7.x

### CODE REVIEW

**Comment by vincepri** [comment]
This will also be backported to v0.6.x and v0.5.x

**Comment by alvaroaleman** [comment]
@vincepri what does that jsonpatch update bring? Did kube update to 0.4.9 as well?

**Comment by vincepri** [comment]
Yes, this latest version has Jordan's fixes, like https://github.com/evanphx/json-patch/pull/108

**Comment by alvaroaleman** [comment]
@vincepri from what I can see, upstream updated to 4.8.0, not 4.9.0: https://github.com/kubernetes/kubernetes/pull/93812

**Comment by vincepri** [comment]
The v0.4.9 release is more recent and carries other bug fixes as well. The v0.4.8 release cannot be used in controller-runtime because it's not addressable by tag, only by commit and because we import another jsonpatch library for webhooks, go.mod won't let us use the commit, but it'll resolve to v0.4.2 IIRC.

@liggitt do you have a timeline for updating to v0.4.9 upstream?

**Comment by liggitt** [comment]
already done in master / 1.19: https://github.com/kubernetes/kubernetes/pull/94147

picks open:
* 1.16 - https://github.com/kubernetes/kubernetes/pull/94150
* 1.17 - https://github.com/kubernetes/kubernetes/pull/94149
* 1.18 - https://github.com/kubernetes/kubernetes/pull/94148

**Comment by vincepri** [comment]
Perfect, thank you!

**Pull request merged**
