### PR TITLE
✨ Implement delete collection via delete options

### PR DESCRIPTION
**Pull request by adracus**
implement `CollectionOptions` in `DeleteOptions` that allow to issue a
`DeleteCollection` call under the hood

add tests + examples

Co-Authored-By: Aaron Clawson <Aaron.Clawson@gmail.com>

Edited By directxman12: function naming, rebase

### CODE REVIEW

**Comment by DirectXMan12** [comment]
/hold

while I be frustrating and indecisive.  Don't want to make you miserable by going back and forth with myself :-P

**Comment by DirectXMan12** [comment]
(this is on the [KB 2.0.0 cross-project tracking board though](https://github.com/kubernetes-sigs/kubebuilder/projects/6), so we'll get it in before then)

**Comment by DirectXMan12** [comment]
rebased on top of #536 and edited for wording.

Should be good to go once that merged.  Sorry for all the back and forth

**Comment by mengqiy** [comment]
/lgtm
Waiting for @droot to take a look. So keeping the `hold` label til it's done.

**Comment by droot** [comment]
Yay!!! Feels good to get this merged. This completes the client interface.

**Pull request merged**
