### PR TITLE
fix gomodules.xyz/jsonpatch/v2 not found

### PR DESCRIPTION
**Pull request by cjhpaul**
404 on https://gomodules.xyz/jsonpatch/v2?go-get=1
Sample output below:
go: sigs.k8s.io/controller-runtime@v0.6.3 requires
        gomodules.xyz/jsonpatch/v2@v2.0.1: unrecognized import path "gomodules.xyz/jsonpatch/v2": reading https://gomodules.xyz/jsonpatch/v2?go-get=1: 404 Not Found
        server response: 404 page not found

### CODE REVIEW

**Comment by vincepri** [comment]
Why is this needed? I ran `make modules` yesterday and was able to download and run all the modules in this repository

**Comment by cjhpaul** [comment]
> Why is this needed? I ran `make modules` yesterday and was able to download and run all the modules in this repository

Yeah, I ran yesterday with no issue. I just noticed it just now. Hopefully it's transient but I don't see jsonpatch listed under https://gomodules.xyz/ anymore.

**Comment by jsing157** [comment]
`export GOPROXY=https://proxy.golang.org` should fix it if you add this to your go env

**Comment by vincepri** [comment]
Maybe @tamalsaha can help here?

**Comment by cjhpaul** [comment]
> `export GOPROXY=https://proxy.golang.org` should fix it if you add this to your go env

I feel like it's a workaround.

**Comment by vincepri** [comment]
It seems the package is now called `kmodules.xyz/jsonpath`

**Comment by alvaroaleman** [comment]
Also its not clear if this is the same code. There is no 2.1.0 tag on mattbairds repo

**Comment by tamalsaha** [comment]
https://github.com/gomodules/jsonpatch/tree/release-2.0

**Comment by jsing157** [comment]
@cjhpaul Can you explain why it is a workaround? I do not understand. Thanks!

**Comment by cjhpaul** [comment]
> @cjhpaul Can you explain why it is a workaround? I do not understand. Thanks!

I think using goproxy is a good option to consider. But I think ideally it would have to build fine without using the proxy, which made me think we would have to either revive the broken path (gomodules.xyz/jsonpatch/v2) or find an alternative package. Of course, there could be a better option.
For me, I can probably live with goproxy along with goprivate since I also have private modules.
Hope that answers your question.

Also, it turned out it's working fine as of now. It looks like an intermittent issue, so I will close this.
Thanks all for taking time on this matter.

**Comment by mnencia** [comment]
> Hi,
> The code is where was https://github.com/gomodules/jsonpatch/tree/release-2.0
> 
> We have not changed anything.
> 
> Also the package is available here: https://pkg.go.dev/mod/gomodules.xyz/jsonpatch/v2?tab=versions
> 
> This seems like a issue at OP's network, I guess?

The problem is that gomodules.xyz reply with the content of kmodules.xyz
This is probably due to some misconfiguration of the serving host.

**Comment by tamalsaha** [comment]
I have reployed the app engine config. It should be fixed now. Sorry about the mix up.

**Pull request closed without merging**
