### PR TITLE
⚠️ Remove deprecated "--master" flag

### PR DESCRIPTION
**Pull request by tanjunchen**
Fixes:https://github.com/kubernetes-sigs/controller-runtime/issues/1028
/cc @vincepri

### CODE REVIEW

**Comment by vincepri** [comment]
/hold

Holding until we open the main branch to v0.7

**Comment by vincepri** [comment]
Thank you for doing this!

**Comment by tanjunchen** [comment]
> /milestone v0.7.x
```
pkg/client/config/config.go:34: File is not `goimports`-ed (goimports)
	log                      = logf.RuntimeLog.WithName("client").WithName("config")
```
After I removed apiServerURL, what is the cause of this error?

**Pull request merged**
