### PR TITLE
:sparkles: Add IsZero method to reconcile.Result

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

/assign @alvaroaleman

### CODE REVIEW

**Comment by coderanger** [comment]
Might want to use a pointer receiver to avoid a heap copy? Guessing this intended to be fast :)

**Comment by vincepri** [comment]
@coderanger Having it as a non-pointer makes it possible to use it on a nil variable as well, which was the intent behind it

**Comment by vincepri** [comment]
@coderanger I stand corrected, we do want to have it as a pointer receiver to check if it's nil

**Pull request merged**
