### PR TITLE
:seedling: Give more time for prow / goroutine leak test

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by vincepri** [comment]
Seems with these changes we can make more progress

/assign @alvaroaleman

**Comment by alvaroaleman** [comment]
Failed on second try :( I think we should just put it into a dedicated file, give it its own build tag and do a dedicated `go run` invocation to prevent other tests from interfering

**Comment by vincepri** [comment]
It got closer 😂 !

**Comment by vincepri** [comment]
@alvaroaleman Let's see if this + the updated CPU requests work out better

**Comment by vincepri** [comment]
Closing in favor of #1070

/close

**Pull request closed without merging**
