### PR TITLE
:warning: Drop rest client request latecy metric

### LINKED ISSUE #1423: Disable rest client latency metric
We vendor in `controller-runtime` and use it to expose its controller specific metrics in addition to our own.
Recently we observed that [rest_client_request_latency_seconds](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/client_go_adapter.go#L55-L60) was eating up a significant portion of Prometheus storage, as can be seen from a snapshot of the highest cardinality metrics in our codebase:
```
42765 kube_secret_type
42799 kube_secret_metadata_resource_version
461312 rest_client_request_latency_seconds_count
461312 rest_client_request_latency_seconds_sum
5074432 rest_client_request_latency_seconds_bucket
```

I understand this metric was deprecated in kube 1.14 and turned off in [1.17](https://github.com/kubernetes/kubernetes/pull/83836).
Is it possible to either disable this metric or to allow us to unregister it?

### PR DESCRIPTION
**Pull request by 2uasimojo**
Remove the `rest_client_request_latency_seconds` metric.

This metric has been deprecated since kube 1.14 and [turned off in kube 1.17](https://github.com/kubernetes/kubernetes/pull/83836).

fixes #1423

Co-Authored-By: @suhanime

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
This is going to break a bunch of people who alert off of this metric, is that going to be okay?

**Comment by 2uasimojo** [comment]
> This is going to break a bunch of people who alert off of this metric, is that going to be okay?

This is where it would help me to understand what the actual effect of https://github.com/kubernetes/kubernetes/pull/83836 was. Wouldn't *that* have already broken such consumers?

**Review by alvaroaleman — COMMENTED** [review]
/ok-to-test

**Comment by logicalhan** [comment]
> This is where it would help me to understand what the actual effect of [kubernetes/kubernetes#83836](https://github.com/kubernetes/kubernetes/pull/83836) was. Wouldn't _that_ have already broken such consumers?

We actually have a deprecation policy, we announce a metric deprecation, we use our prometheus wrapper to annotate our metrics, our framework, on a version bump will auto-hide the metric (which yes breaks consumers). However, they can re-enable it for a release in order to properly migrate off of it. After that, the metric is deleted. 

We offer a staged way to softly push people from using a metric that we intend to delete, in this PR, it'll just abruptly break people...

**Comment by alvaroaleman** [comment]
> This is going to break a bunch of people who alert off of this metric, is that going to be okay?

@logicalhan is that an assumption or do you personally know of a case where someone uses this? The metric includes the whole url as a label, which is obviously a cardinality problem

**Comment by logicalhan** [comment]
> @logicalhan is that an assumption or do you personally know of a case where someone uses this? The metric includes the whole url as a label, which is obviously a cardinality problem

I'm assuming people use recording rules to aggregate the metric into something more useable.

**Comment by logicalhan** [comment]
FYI (We also have a way to enforce cardinality bounds): https://github.com/kubernetes/enhancements/pull/1692

**Comment by logicalhan** [comment]
We try really, really hard not to break people upstream...

**Comment by alvaroaleman** [comment]
> We try really, really hard not to break people upstream...

Sure but deactivating a metric and forcing ppl to do sth to get it back is always going to break them. I am also fine with adding an explicit opt-in for this and removing it in a future release, but the only value add I see in that is for cases where ppl use this metric and don't know how to properly the code that is currently being removed.

**Comment by 2uasimojo** [comment]
Okay; if either

> recording rules

or

> a way to enforce cardinality bounds

allows us to effectively nix this metric from taking up space, we're happy to do that. What does the former look like? /me starts reading the latter...

**Comment by 2uasimojo** [comment]
> adding an explicit opt-in for this

like this? https://github.com/kubernetes-sigs/controller-runtime/pull/1587

**Comment by logicalhan** [comment]
> Sure but deactivating a metric and forcing ppl to do sth to get it back is always going to break them. 

Yes but in order to unbreak in this case is to roll-back a version. In our case, you just need to enable a flag. This means you can bump the version and use it in an unbroken way, but you must now explicitly acknowledge that this metric is not one you can depend on in a future release. It is a forcing function which is softer than, you can't use this release if you can't tolerate not having this metric.

**Comment by logicalhan** [comment]
> > adding an explicit opt-in for this
> 
> like this? #1587

Yeah I probably prefer the optional approach, it's softer and friendly to users.

**Comment by 2uasimojo** [comment]
Okay, let's pursue this via #1587 (or something like it). Thanks!

**Pull request closed without merging**
