### PR TITLE
✨ Bump dependencies for Kubernetes 1.16.2

### PR DESCRIPTION
**Pull request by munnerz**
Bump dependencies for Kubernetes 1.16.2.

This currently pins to the `kubernetes-1.16.2` branch.

### CODE REVIEW

**Comment by awesomenix** [comment]
@munnerz checking if its still being worked on, our project is going to update to 1.16 soon, would be helpful if this gets merged.

**Comment by marun** [comment]
@munnerz Please update this PR to target `kubernetes-1.16.0`. `controller-tools` has already been updated which leaves `controller-runtime` as the blocker for those using kubebuilder and wanting to update deps to 1.16.

**Comment by enxebre** [comment]
friendly ping @munnerz :)

**Comment by munnerz** [comment]
I've updated this PR to target `kubernetes-1.16.2` and rebased on master since Gopkg.* changes 😄 

/hold cancel

**Comment by munnerz** [comment]
Ah, seems https://github.com/kubernetes-sigs/controller-runtime/pull/618 has already merged, but this at least bumps to the `.2` patch release 😅 thanks @enxebre!

**Comment by enxebre** [comment]
> I've updated this PR to target kubernetes-1.16.2 and rebased on master since Gopkg.* changes 😄

sweet! probably want to update the PR desc as well

**Comment by DirectXMan12** [comment]
updated the PR desc, but looks like tests are failing

**Comment by munnerz** [comment]
Closing in favour of #732

**Pull request closed without merging**
