### PR TITLE
🐛 Start web hooks first

### PR DESCRIPTION
**Pull request by fabriziopandini**
This PR test a simpler and possible cleaner solution to #1685.
We should test how this impact start time

### CODE REVIEW

**Comment by fabriziopandini** [comment]
I will take a look about tests tomorrow morning, at least this is a chance to learn this part as well

**Comment by alvaroaleman** [comment]
> @alvaroaleman When I first moved the code to run webhooks first there wasn't a nice way to do it from the outside.

Maybe just set up a manager with a webhook and a runnable that does a http request to the webhook in its `Start()`? It is a bit annoying because if we race like before it will flake and not reliably fail, but I guess that is unavoidable when it comes to race conditions that are not data races?

**Comment by fabriziopandini** [comment]
@vincepri rebased on to of the release 0.10 branch

**Comment by sbueringer** [comment]
@fabriziopandini Can you please include the change in: https://github.com/fabriziopandini/controller-runtime/pull/1 ?

The problem is that otherwise we'll have the same deadlock just with the healthprobes.

I would then take this version and rebase my 2 test PRs iN CAPI to run all our tests with and without leader election

**Comment by fabriziopandini** [comment]
> @fabriziopandini Can you please include the change in: fabriziopandini#1 ?

Done!

**Comment by sbueringer** [comment]
Thx! Tests are running here:
* https://github.com/kubernetes-sigs/cluster-api/pull/5421
* https://github.com/kubernetes-sigs/cluster-api/pull/5407

P.S. I might need a few tries, just refactored those branches back to use CR release-0.10 instead of main.

**Comment by sbueringer** [comment]
@fabriziopandini WDYT, ready for review/squash/un-wip? :)

**Review by vincepri — APPROVED** [review]
/lgtm
/milestone v0.10

**Pull request merged**
