### PR TITLE
:sparkles: Client option types implement client option interfaces

### PR DESCRIPTION
**Pull request by alvaroaleman**
Currently setting multiple `ListOption`s is pretty annoying, because it is not defined as a function but as an interface, which can not be defined inline.

This PR extends the existing `ListOptions` struct to implement the `ListOption` interface to allow using it as a `ListOption`.

If anyhow possible, I'd be super, super glad if we could get this into the `release-0.2` branch as well :grimacing: 

/assign @DirectXMan12

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Happy to backport (IIRC, we haven't made any breaking changes yet, so releasing is going to be more-or-less just FF to master for a bit).  Do you mind doing this for the rest of the options types too?  That way we have consistency.

**Comment by DirectXMan12** [comment]
But yeah, this seems pretty reasonable

**Comment by alvaroaleman** [comment]
@DirectXMan12 updated the PR to make all the option types implement the corresponding interfaces.

Obviously I am pretty late to the party to mention that, but I think there is a reason ppl commonly use option funcs and not option interfaces..We can probably think about that for a v0.3

**Comment by alvaroaleman** [comment]
@DirectXMan12 should I create a cherrypick PR for the release-0.2 branch?

**Comment by DirectXMan12** [comment]
We'll pull it in as part of the next release -- we generally don't need to cherry-pick until we start breaking things, and I don't think we've merged anything breaking.

You can do a release PR though -- just ask for a merge of master into release-0.2, and check the release notes by running

```bash
$ git checkout release-0.2
$ git merge master
$ ./hack/release/release-notes.sh
```

**Pull request merged**
