### PR TITLE
🌱 Provide more information on deprecating ComponentConfig

### PR DESCRIPTION
**Pull request by vincepri**

### CODE REVIEW

**Comment by FillZpp** [comment]
/lgtm
/hold
for other reviews

When do we plan to remove the ControllerManagerConfiguration?

**Comment by vincepri** [comment]
@FillZpp We could aim for N+2 versions after the deprecation goes out?

**Comment by FillZpp** [comment]
> @FillZpp We could aim for N+2 versions after the deprecation goes out?

Alright, sounds good!
/hold cancel

**Pull request merged**
