### PR TITLE
🌱 Update k8s API to v1.25

### PR DESCRIPTION
**Pull request by Fedosin**
Kubernetes v1.25 has been released, so we can update our dependencies.

Signed-off-by: Mikhail Fedosin <mfedosin@redhat.com>

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by sbueringer** [comment]
@alvaroaleman I assume we want to bump our jobs to Go 1.19 (Kubernetes v1.25 is using Go 1.19?)

for reference if someone wants to pick that up:
* https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-runtime/controller-runtime-periodics-master.yaml
* https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-runtime/controller-runtime-presubmits-master.yaml

**Comment by alvaroaleman** [comment]
> @alvaroaleman I assume we want to bump our jobs to Go 1.19 (Kubernetes v1.25 is using Go 1.19)?

Yes, please

**Comment by laxmikantbpandhare** [comment]
> @alvaroaleman I assume we want to bump our jobs to Go 1.19 (Kubernetes v1.25 is using Go 1.19)?
> 
> for reference if someone wants to pick that up:
> 
> * https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-runtime/controller-runtime-periodics-master.yaml
> * https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-runtime/controller-runtime-presubmits-master.yaml
> * https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-tools/controller-tools-presubmits-master.yaml

I can take a look into if that is okay.

**Comment by laxmikantbpandhare** [comment]
@alvaroaleman @sbueringer PTAL

Created PR for the same- https://github.com/kubernetes/test-infra/pull/27258

**Comment by tamalsaha** [comment]
Thank you! I would appreciate a new tag/release is done!

**Comment by sbueringer** [comment]
I think we should wait for ginkgo v2, Go 1.19 and the golangci-lint bump.

**Pull request merged**
