### PR TITLE
 🐛 Better UserAgent for leader-election client

### PR DESCRIPTION
**Pull request by jdef**
suffix the leader-election client with `/leader-election` for better auditing

### CODE REVIEW

**Comment by alenkacz** [comment]
/lgtm

👋 High James :) Long time no see...

**Comment by jdef** [comment]
> /lgtm
> 
> 👋 High James :) Long time no see...

Hi, Alena! Hope you're doing well.

**Comment by jdef** [comment]
@alenkacz mind giving this an "ok to test" label?

**Comment by jdef** [comment]
can someone add the "ok-to-test" label here, please?

**Comment by jdef** [comment]
thanks, can someone please /approve this?

**Comment by vincepri** [comment]
Code changes look good, mind squashing commits before we merge it?

**Comment by alvaroaleman** [comment]
/label tide/merge-method-squash
Let github do the squashing

**Pull request merged**
