### PR TITLE
📖 CR-855: added example of probes usage with controller

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Solves #855

### CODE REVIEW

**Comment by alexeldeib** [comment]
makes sense to me! dropped this into a main.go and tested locally, seems good.

/ok-to-test
/lgtm

**Comment by omerlh** [comment]
What is `healthz.Ping`? I was wondering what I should put there :)

**Comment by christopherhein** [comment]
@omerlh https://github.com/kubernetes-sigs/controller-runtime/blob/v0.5.1/pkg/healthz/healthz.go#L188

**Comment by omerlh** [comment]
I would consider changing the name - Ping is not what I was expecting this function to do. Maybe just `ok` or `dummy`?

**Pull request closed without merging**
