### PR TITLE
🌱 OWNERS_ALIASES: move fillzpp to maintainers

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

Moves me (@FillZpp ) to maintainers to improve coverage for maintainer-requiring tasks, e.g. making releases (following [RELEASE.md](https://github.com/kubernetes-sigs/controller-runtime/blob/master/RELEASE.md), thanks to @camilamacedo86 ).

### CODE REVIEW

**Comment by FillZpp** [comment]
Hey guys @alvaroaleman @joelanford @vincepri @camilamacedo86 , what do you think?

Please let me know if there’s anything else I should do. Your suggestions are very appreciated :)

**Comment by FillZpp** [comment]
> It really needs to be with them. I am more on the Kuebuilder side of the world.
> In Kubebuilder we do have not the maintainers field (we only have https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/CONTRIBUTING-ROLES.md + admin), not sure how it has been defined/categorized here.

Thanks, I understand. Although it seems Kubebuilder has both [admin](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-api-machinery/teams.yaml#L101) and [maintainer](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-api-machinery/teams.yaml#L134) roles.But controller-runtime (and controller-tools) are mostly using maintainer role, the admin list seems to be obsolete.

**Review by varshaprasad96 — APPROVED** [review]
+1! 
/lgtm

**Review by alvaroaleman — APPROVED** [review]
/hold

I am in favor of this. @joelanford @vincepri any objections?

**Comment by vincepri** [comment]
Hey folks, just looking through this issue, I'm generally in favor of promoting new members to have a larger footprint in the community. That said, going by the community guidelines https://github.com/kubernetes/community/blob/master/community-membership.md I don't think we're quite there yet by looking at the amount of contributions done so far, or reviews. 

If this is mostly about releases, I'd suggest that we work on automating the release process as much as possible through github actions, and have it self contained, like we did in the Cluster API project.

**Comment by FillZpp** [comment]
> Hey folks, just looking through this issue, I'm generally in favor of promoting new members to have a larger footprint in the community. That said, going by the community guidelines https://github.com/kubernetes/community/blob/master/community-membership.md I don't think we're quite there yet by looking at the amount of contributions done so far, or reviews.

Oh, thanks for your feedback. I can add some information:

- I have [posted 10+ PR and been merged](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=+is%3Apr+author%3AFillZpp+), also I'm still working on some features like stoppable controllers/watches. This is partly due to the fact that there just aren't many of big changes in the project nowadays, but I'm still willing to make it better continuously.
- I have [been part of 50+ issues](https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+involves%3AFillZpp+), discussing, answering questions.
- I have [involved and assigned in 80+ PPs](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+involves%3AFillZpp), in most of them I helped review and gave my suggestions.

@vincepri Not sure which requirements you mentioned I'm still not reached from the membership doc. Could you please make it clear so that I could make my efforts towards it?

Thanks!

**Comment by vincepri** [comment]
@FillZpp Thank you for the summary! I've missed a lot of these when I looked around. 

LGTM, can we move though from maintainer to approver list?

**Comment by vincepri** [comment]
Superseded by https://github.com/kubernetes-sigs/controller-runtime/pull/2088

/close

**Pull request closed without merging**
