### PR TITLE
🌱 Refactor typed_client and unstructured_client to be consistent

### PR DESCRIPTION
**Pull request by hyschumi**
this pr just update some code , make  unstructured_client and typed_client  have same code style.
i think the code will be more readable for users.

### CODE REVIEW

**Review by AlmogBaku — APPROVED** [review]
LGTM

**Review by vincepri — APPROVED** [review]
/approve

**Comment by vincepri** [comment]
/retitle 🌱 Refactor typed_client and unstructured_client to be consistent

**Pull request merged**
