### PR TITLE
:running: Remove unused attributes from controller

### PR DESCRIPTION
**Pull request by alvaroaleman**
This removes a set of unused attributes from the controller.

### CODE REVIEW

**Comment by vincepri** [comment]
@DirectXMan12 Any reason why these fields were included in the first place?

**Comment by DirectXMan12** [comment]
IIRC, it has to do with injection into the reconciler -- at least Scheme was commonly injected as opposed to directly being passed in, at least in the early days.  We'll prob want to figure something out before 1.0.0 wrt that.

Right now, we prob don't want to remove those without double-checking that the corresponding injection still works

**Comment by alvaroaleman** [comment]
@DirectXMan12 they do work, otherwise this PR wouldn't compile as the corresponding attributes are gone.

The injection is done by just storing the `SetFields` from the manager and re-using it: https://github.com/kubernetes-sigs/controller-runtime/pull/940/files#diff-3c862eb54a8e0e161b534e0c67e5379eL113

**Pull request merged**
