### PR TITLE
Add gerred as reviewer

### PR DESCRIPTION
**Pull request by gerred**
I have participated in several PRs now, tested out dependencies, and am active in supporting users in #kubebuilder and #kubernetes-operators. Like the others and as a fellow consumer of controller-runtime that is critical to our project, I'd love to help review!

### CODE REVIEW

**Comment by DirectXMan12** [comment]
minor nit: please rebase in the style of https://github.com/kubernetes-sigs/controller-runtime/pull/690 (with the separate reviewers alias)

**Comment by gerred** [comment]
on it!

**Comment by gerred** [comment]
@DirectXMan12 done!

**Pull request merged**
