### PR TITLE
🌱 Prepare envtest certs for aggregation layer

### PR DESCRIPTION
**Pull request by timebertt**
Prepare API server certs in envtest for usage with the [aggregation layer](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/):
- write CA cert of API server to a file for usage as `--requestheader-client-ca-file` and `--client-ca-file`
- add `ClientAuth` key usage to API server cert, so it can be used by the API server to authenticate against an extension API server

With this change, tests are able to setup the API server's aggregation layer for registering `APIService`s in their test environment.

For example:
```go
testEnv.ControlPlane.APIServer.Args = append(envtest.DefaultKubeAPIServerFlags,
	"--client-ca-file={{ .CertDir }}/apiserver-ca.crt",
	"--proxy-client-key-file={{ .CertDir }}/apiserver.key",
	"--proxy-client-cert-file={{ .CertDir }}/apiserver.crt",
	"--requestheader-client-ca-file={{ .CertDir }}/apiserver-ca.crt",
	"--requestheader-extra-headers-prefix=X-Remote-Extra-",
	"--requestheader-group-headers=X-Remote-Group",
	"--requestheader-username-headers=X-Remote-User",
)
```

These are the minimum required changes to make this scenario work.

Ref #1448

### CODE REVIEW

**Comment by timebertt** [comment]
@alvaroaleman @DirectXMan12 can one of you check this PR?

**Comment by alvaroaleman** [comment]
@DirectXMan12 is currently working on adding TLS support to envtest, maybe we should wait for that?

**Comment by timebertt** [comment]
Hmm, probably makes sense. 
@DirectXMan12 if you want we can then incorporate my changes into your larger PR. 
Let me know if I can help you in any way. Is there already an issue for this?

**Comment by timebertt** [comment]
friendly ping to @DirectXMan12

**Comment by timebertt** [comment]
@alvaroaleman @DirectXMan12 how do we proceed here? 
Should we just get this small change in for the time being?

**Comment by DirectXMan12** [comment]
hey, I'm sorry for dropping this one, I'll figure out what to do with this shortly -- lost track of some PRs.  Btw, if this happens again, please do ping me on slack -- I occasionally lose track of github notifications.

**Comment by timebertt** [comment]
@DirectXMan12 Ok, will ping you on slack next time :)
Thanks for coming back to this PR. I'll have a look at https://github.com/kubernetes-sigs/controller-runtime/pull/1486 in the meantime and check what is missing there for the aggregation layer use case.

**Comment by timebertt** [comment]
Currently working on upgrading to controller-runtime@v0.9.0 (https://github.com/gardener/gardener/issues/4174). Will figure out what to do with this PR during that.

**Comment by timebertt** [comment]
After upgrading to controller-runtime@v0.9.0, I adapted our configuration of the aggregation layer to https://github.com/kubernetes-sigs/controller-runtime/pull/1541 and decided to *not* reuse the client certs and generate dedicated front-proxy CA/cert/key instead (which is also cleaner) – reusing the client certs was more a quick and dirty solution actually. With that, this PR is not required anymore, so
/close

You can find the updated example for how to configure the aggregation layer in envtest [here](https://github.com/gardener/gardener/blob/db7118fe6a9072e462b32fe9aea92bdc11c88bf2/pkg/envtest/aggregator.go#L35).

**Pull request closed without merging**
