### PR TITLE
Add 'kensipe' as reviewer

### PR DESCRIPTION
**Pull request by kensipe**
I've provided a number of reviews and code including the bump to kube 1.16

Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

**Comment by gerred** [comment]
I asked Ken to review #777, #776, and #773. He's been active in the past, but super excited for him to get those active. Pending these steps, @alenkacz will you lgtm this? and then I'm happy to approve. Welcome aboard! ⛵️

**Comment by alenkacz** [comment]
👍 

/lgtm

**Comment by kensipe** [comment]
rebased based on label

**Comment by gerred** [comment]
Thanks for your continued work on reviewing, and thanks for your stewardship of this ecosystem. As soon as #774 lands I will approve this PR.

**Comment by DirectXMan12** [comment]
I'm not necessarily against this, but I'd prefer to see a couple (doesn't need to be a ton, just a couple) more substantial PRs/contributions before marking as official reviewer (if I've missed or forgotten a few, feel free to let me know) -- see https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/CONTRIBUTING-ROLES.md#becoming-a-reviewer

**Comment by kensipe** [comment]
sure thing @DirectXMan12  I was out on PTO but back to active status

**Pull request closed without merging**
