### PR TITLE
✨Upgrade k8s dependencies from 1.23.0 to 1.23.5

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
This Bumps all k8s dependencies.
PR was made for Bumping k8s 1.23.3 to get bug fixes in kubernetes-sigs/kubebuilder https://github.com/kubernetes-sigs/kubebuilder/issues/2502, these changes are required before we can do that.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
They were added because you created the PR against the wrong branch, `master` instead of 0.11. Please run `go mod tidy` to get the `go,sum` file fixed up

**Comment by NikhilSharmaWe** [comment]
@alvaroaleman Just pinging that PR is ready to be merged.

**Review by alvaroaleman — APPROVED** [review]

**Review by Oilysxewe204 — COMMENTED** [review]
https://twitter.com/Oilysxewe204

**Pull request merged**
