### PR TITLE
✨ Bump golang version to 1.19

### PR DESCRIPTION
**Pull request by laxmikantbpandhare**
IIRC upstream kubernetes/kubernetes updated the golang version to 1.19 and we are following the same.

It will update the go lang version to 1.19

I already Updated `test-infra` jobs for `controller-runtime` and `controller-tools` to 1.19 PR is here: https://github.com/kubernetes/test-infra/pull/27258

### CODE REVIEW

**Comment by sbueringer** [comment]
I think we shouldn't bump the version. If I'm correct this would force all consumers of CR to use Go 1.19 as well.

As long as CR itself doesn't need Go 1.18/19 features it would be better to keep 1.17.

**Comment by sbueringer** [comment]
> I think we shouldn't bump the version. If I'm correct this would force all consumers of CR to use Go 1.19 as well.
> 
> As long as CR itself doesn't need Go 1.18/19 features it would be probably better to keep 1.17.

Hm looks like k/k uses Go 1.19 now: https://github.com/kubernetes/kubernetes/blob/v1.25.0/go.mod#L9
I guess then it doesn't really matter if we upgrade as well?

**Comment by laxmikantbpandhare** [comment]
> > I think we shouldn't bump the version. If I'm correct this would force all consumers of CR to use Go 1.19 as well.
> > As long as CR itself doesn't need Go 1.18/19 features it would be probably better to keep 1.17.
> 
> Hm looks like k/k uses Go 1.19 now: https://github.com/kubernetes/kubernetes/blob/v1.25.0/go.mod#L9 I guess then it doesn't really matter if we upgrade as well?

I checked with @alvaroaleman and decided to follow the suit as it is updated k/k upstream

**Comment by alvaroaleman** [comment]
I think we need to bump golangci-lint to a version with go 1.19 similiar to https://github.com/kubernetes-sigs/controller-runtime/pull/1976

That I think might also entail some go fmt changes

**Comment by alvaroaleman** [comment]
Strictly speaking the above is orthogonal to this change and caused by bumping the go version in the presubmit, but we won't be able to merge anything until we do it :upside_down_face:

**Comment by laxmikantbpandhare** [comment]
> I think we need to bump golangci-lint to a version with go 1.19 similiar to #1976
> 
> That I think might also entail some go fmt changes

Yup definitely

**Comment by sbueringer** [comment]
@alvaroaleman @laxmikantbpandhare Is there already someone working on the golangci-lint bump? Otherwise I can help out.

**Comment by laxmikantbpandhare** [comment]
> @alvaroaleman @laxmikantbpandhare Is there already someone working on the golangci-lint bump? Otherwise I can help out.

I haven't started yet. If you want you can update or else I will add in this same PR.

**Comment by sbueringer** [comment]
> > @alvaroaleman @laxmikantbpandhare Is there already someone working on the golangci-lint bump? Otherwise I can help out.
> 
> @sbueringer - I haven't started yet. If you want you can update.

On it

**Comment by sbueringer** [comment]
Fix PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1987

**Comment by laxmikantbpandhare** [comment]
The `certwatcher` test suit is failing.

**Comment by laxmikantbpandhare** [comment]
Looks like the retest worked. @alvaroaleman @sbueringer - Could you please take a look and approve the changes.

**Comment by alvaroaleman** [comment]
@laxmikantbpandhare there is a merge conflict now, can you please rebase?

**Comment by laxmikantbpandhare** [comment]
> @laxmikantbpandhare there is a merge conflict now, can you please rebase?

@alvaroaleman Did the rebase.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
