### PR TITLE
:warning: Update Kubernetes client libraries to 1.15.0 release

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
In cluster-api project, we are looking to switch to go.mod, v2 project strucutre, k8s 1.15.0 in one sweap. 

xref: https://github.com/kubernetes-sigs/cluster-api/issues/1025

**Comment by vincepri** [comment]
Are there any major blockers to get this merged? 1.15 brings beta support for CustomResourceWebhookConversion :)

**Comment by tamalsaha** [comment]
@DirectXMan12 , pr is ready for review. I have fixed the conflicts from the jsonpatch fix.

**Comment by jimmidyson** [comment]
FWIW... LGTM... I'd like to see these libraries updated for 1.15.0 ASAP too.

**Comment by DirectXMan12** [comment]
whoops, looks like there's an extra commit, and you've checked in the vendor directory, which we stopped doing.

**Comment by tamalsaha** [comment]
@DirectXMan12 , it is fixed now. I think `vendor` folder should be added to  `.gitignore` file.

**Comment by tamalsaha** [comment]
@DirectXMan12 / @mengqiy / @droot , anyone mind taking a look? Are there any blockers to getting this merged?

**Comment by vincepri** [comment]
Any updates on this?

**Comment by LiliC** [comment]
@tamalsaha @DirectXMan12 I think we should hold off on this, until after the `v0.2.0` release is cut, that way we have a release that bumps to the kubernetes version`1.14`. Otherwise, we need a separate release that cherry-picks this one out and that might be a bit more difficult.

**Comment by DirectXMan12** [comment]
/hold

we'll do a couple releases in quick succession for this (v0.2.0 and v0.2.1) assuming there's nothing breaking here (will need to double-check, but I don't think so).

**Comment by seh** [comment]
I'm not sure if it's related, but #500—though closed—describes some version incompatibilities with the dependencies.

**Comment by magrossm** [comment]
> I'm not sure if it's related, but #500—though closed—describes some version incompatibilities with the dependencies.

@all, I just installed and I also get the cannot find /appscode/jsonpatch message. Is it going to be fixed since the issue was closed. Afaisee still a problem.

**Comment by tamalsaha** [comment]
@magrossm , this library now lives here: https://github.com/gomodules/jsonpatch

You should use `gomodules.xyz/jsonpatch@v2.0.1`

**Comment by tamalsaha** [comment]
Folks, I am not looking to further work on this pr. So, I am closing this. Feel free to copy/create a new pr.

**Comment by magrossm** [comment]
> @magrossm , this library now lives here: https://github.com/gomodules/jsonpatch
> 
> You should use `gomodules.xyz/jsonpatch@v2.0.1`

Yes but how do I bind it in? I want to install clusterapi clusterctl and I cannot find go.mod.

`$ git clone https://github.com/kubernetes-sigs/cluster-api $GOPATH/src/sigs.k8s.io/cluster-api
$ cd $GOPATH/src/sigs.k8s.io/cluster-api/cmd/clusterctl/
$ go build`

**Comment by DirectXMan12** [comment]
Yeah, sorry about all the delay @tamalsaha.  We'll prob pick this up shortly now that v2 is out.

**Comment by DirectXMan12** [comment]
@magrossm please ask the cluster-api folks.  They're probably using dep (if you see a Gopkg.tom file)

**Pull request closed without merging**
