### PR TITLE
pkg/client/fake/client.go: get gvk without potential panic in List()

### LINKED ISSUE #168: Panic in fake client
I tried to write unit tests using the fake client and `List()` panics reliably when accessing `opts.Raw`:

https://github.com/kubernetes-sigs/controller-runtime/blob/ddf0390deebe496cb449b1b8540031da9236afa2/pkg/client/fake/client.go#L80-L82

Why `opts.Raw` must be filled (it's not necessary when using the real client) and why it's `TypeMeta` should have any value?

If I understand the code (and I probably don't), it expects `opts.Raw.TypeMeta.GroupVersionKind()` to be the kind of items in returned list, not the list itself (i.e. Pod instead of PodList). Such requirement looks very odd.

### PR DESCRIPTION
**Pull request by estroz**
Unless `opts.Raw.TypeMeta` is explicitly populated, `client.List()` panics. As noted in #168, population is not necessary outside of the fake client. This simple fix does essentially the same thing as [`unstructuredClient.List()`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/unstructured_client.go#L114-L117).

Closes #168

### CODE REVIEW

**Comment by estroz** [comment]
Signed

**Comment by sverrirsig** [comment]
Thank you! - List() now works perfectly 👍

**Comment by grantr** [comment]
This is quite similar to #213. :smiley:

**Comment by estroz** [comment]
@grantr yes your solution looks better. I'll close this if @DirectXMan12 @droot give the ok.

**Comment by droot** [comment]
@estroz Thanks for submitting this fix. Took at a look at #213 which also addresses this issue and improves the code/tests also, so lets close this in favor of #213 .

**Pull request closed without merging**
