### PR TITLE
:sparkles: Bump k8s dependencies to 1.20

### PR DESCRIPTION
**Pull request by varshaprasad96**
Bump k8s dependencies to 1.20

Update: Updated the PR to use k8s 1.20.
Note: This PR currently bumps the Kubernetes dependencies to v1.20.0-beta.1 release. This will be updated once a stable 1.20 release is out.

### CODE REVIEW

**Comment by joelanford** [comment]
/hold

Until `v0.7.0` is released.

**Comment by joelanford** [comment]
/retitle :sparkles: Bump k8s dependencies to 1.20

**Comment by estroz** [comment]
@vincepri @alvaroaleman @DirectXMan12 can we get this reviewed/merged then cut v0.8.0 this week?

**Review by alvaroaleman — APPROVED** [review]
/approve

**Pull request merged**
