### PR TITLE
lets controllerManager.start() return instead of blocking

### PR DESCRIPTION
**Pull request by mhrivnak**
It always gets called as a goroutine, so nothing expects it to block. This
change slightly simplifies the code and lets the goroutine die instead of
keeping it around forever.

### CODE REVIEW

**Comment by mhrivnak** [comment]
The diff looks more complex than it is. It just:
1. removes the `select` from the bottom
2. removes the inner `func()` block

Everything else is untouched except moving the indentation left.

When viewing it, if you click "Diff settings" and select "Hide whitespace changes", you'll see there's not much to it.

**Comment by droot** [comment]
Looks good to me. Would like @JoelSpeed to take a look just to ensure this change plays nicely with the leaderElection code that we have in `manager.Start()`.

**Comment by droot** [comment]
Another thing I noticed that while using leader election, leaderElector passes its own stop channel to `cm.start`, so not sure if that leads to unexpected behavior. Also, the code for leader election in `cm.Start` sort of looks complex with multiple go routines and select blocks. /cc @JoelSpeed @mhrivnak @DirectXMan12

**Comment by droot** [comment]
> I don't think this does. When the leader elector loses leader it closes the channel and sends an error which in turn causes cm.Start to return the error, exiting the controller. If stop passed to cm.Start is closed then the function returns as well in theory closing the controller, we don't at this point then close the leader electors stop channel which I guess could cause problems, this could be avoided with a little refactor though. Want me to do that and make sure we ignore the leader elector's stop channel?

Took a quick look a the leader elector lib, ignoring the leader elector's stop channel is fine as long as we exit when we stop leading (which we do as you explained above). I saw you made another PR, will take a look.

**Pull request merged**
