### PR TITLE
✨ Bump k8s v0.25.0-alpha.3

### PR DESCRIPTION
**Pull request by jmrodri**
Signed-off-by: jesus m. rodriguez <jesusr@redhat.com>

Fixes: #1966

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by joelanford** [comment]
/approve cancel

Ping me again when the tests are passing and I'll take another look!

**Comment by jmrodri** [comment]
@joelanford oof sorry didn't see they were failing. I ran them locally. I'll investigate them.

**Comment by jmrodri** [comment]
@joelanford @camilamacedo86 tests passed

**Review by camilamacedo86 — APPROVED** [review]
/approved

**Comment by camilamacedo86** [comment]
Adding the label since it was aproved/lgtm already and the issue was a flake in the ci.

**Pull request merged**
