### PR TITLE
:running: Update golangci-lint to 1.47.3

### PR DESCRIPTION
**Pull request by alvaroaleman**
Updates golangci-lint in github actions

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Seems the latest version wants to gofmt in the (incompatible) go 1.19 style, I went back one version to not have go 1.19 support as the repo is tested with go 1.18, lets see how that goes

**Comment by alvaroaleman** [comment]
The error assertions in the dynamic rest mappers checkAndReload never worked and fixing them makes the tests fail :/

**Comment by alculquicondor** [comment]
/lgtm
/hold
in case you would like to have a review from an experienced contributor to this repo.

**Comment by alvaroaleman** [comment]
I think this is fine, as can be seen by the prior failures this has a very good test coverage
/hold cancel

**Pull request merged**
