### PR TITLE
:seedling: Move directxman12 to approvers-emeritus

### PR DESCRIPTION
**Pull request by DirectXMan12**
As per
https://groups.google.com/g/kubebuilder/c/-5hOFa_adr4/m/Sp_Zb755AwAJ

### CODE REVIEW

**Comment by DirectXMan12** [comment]
/hold

till the end of the week in case I need to do any last minute hand-off stuff

**Comment by christopherhein** [comment]
@DirectXMan12 thank you so much for all of your work across so many projects in the k8s space and everything you have done with controller-runtime/kubebuilder. You have been an inspiration to many, myself included, I look forward to seeing what you are up to next!
❤️ ❤️ ❤️

**Comment by vincepri** [comment]
/lgtm

but really not ❤️ Thank you Solly for your hard work and leadership

**Pull request merged**
