### PR TITLE
⚠️  RESTMapper: don't treat non-existing GroupVersions as errors

### PR DESCRIPTION
**Pull request by ary1992**
/kind bug

This PR fixes the new RESTMapper implementation to properly handle cases where an API Group / GroupVersion is not present in the system. Clients expect No{Kind,Resource}MatchErrors in this case.

The first commit increases the accuracy of the RESTMapper tests to verify the described expectations.
The second commit implements the actual fix.

The changes are from @timebertt PR https://github.com/kubernetes-sigs/controller-runtime/pull/2425. 
The PR #2425 is still needed as with non existing CRDs  we are getting `failed to find API group` error.

### CODE REVIEW

**Comment by ary1992** [comment]
cc @alvaroaleman

**Comment by vincepri** [comment]
/hold

This is in direct contrast with hold

**Comment by ary1992** [comment]
> This is in direct contrast #2424

WDYM ? We still need this fix right? refer https://github.com/kubernetes-sigs/controller-runtime/pull/2425#issuecomment-1725606042 . PR #2425 was closed saying it was fixed with #2472 but that is not the case. The issue is still there.

**Comment by alvaroaleman** [comment]
Wasn't this issue already fixed by https://github.com/kubernetes-sigs/controller-runtime/pull/2472 ?

**Comment by ary1992** [comment]
> Wasn't this issue already fixed by #2472 ?

I don't think so
https://github.com/kubernetes-sigs/controller-runtime/pull/2425#issuecomment-1725606042

**Comment by akalenyu** [comment]
gentle ping :pray: @alvaroaleman

**Comment by sbueringer** [comment]
Hm are we okay with the cache filling up with invalid groups after this change?

image

**Comment by alvaroaleman** [comment]
> Hm are we okay with the cache filling up with invalid groups (that we didn't find) after this change?

I guess the alternate is to handle absence of an entry in the map? Not sure if it will matter too much in practise as there isn't too much data in a group and this will only happen when requesting an absent group.

**Pull request merged**
