### PR TITLE
:sparkles: Bump k8s deps to 1.27.7

### PR DESCRIPTION
**Pull request by varshaprasad96**

### CODE REVIEW

**Comment by varshaprasad96** [comment]
Investigating the failed test

**Comment by sbueringer** [comment]
/hold cancel

IIRC one of the usual flakes

**Comment by varshaprasad96** [comment]
@sbueringer This test was failing locally for me with a 5 sec timeout. But with 10 sec, it seems to pass.

```
➜  controller-runtime git:(bump/k8s-1.27.7) ✗ go test -race sigs.k8s.io/controller-runtime/pkg/internal/testing/process
ok  	sigs.k8s.io/controller-runtime/pkg/internal/testing/process	4.514s
```

If this is an expected flake, I would not want to increase the stop timeout any further.

**Comment by sbueringer** [comment]
/hold cancel

Let's see what Prow says

**Pull request merged**
