### PR TITLE
Prepare for v0.5.9

### PR DESCRIPTION
**Pull request by vincepri**
/assign @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@vincepri the graceful shutdown PR means that we now block when we didn't. Would it make sense to default the waitPeriod to 0 seconds for reelase-0.5 to keep the behavior consistent while still allowing to opt into the feature?

**Comment by vincepri** [comment]
@alvaroaleman Removed the graceful shutdown commits, given that it was built on top of other commits that can't be backported (metrics server, leader election changes)

**Comment by vincepri** [comment]
Yay finally passed 🎉

**Pull request merged**
