### PR TITLE
⚠ Move arguments from Watch() & Start() to Source objects

### PR DESCRIPTION
**Pull request by inteon**
⚠️ depends on https://github.com/kubernetes-sigs/controller-runtime/pull/2686

This PR removes the argument pass-through that happens when starting a Source watch.
Now, the `eventhandler` is passed directly to the Source constructor function.
Additionally, the `predicates` are now passed to the `handler.WithPredicates` which returns a "filtered handler".

This UX change makes the setup of Sources more intuitive, makes it much easier to create a custom Source and makes Sources easier to reason about.

### CODE REVIEW

**Comment by sbueringer** [comment]
@inteon Are you still interested in this PR?

**Comment by inteon** [comment]
@sbueringer I rebased the PR.

**Comment by inteon** [comment]
A similar change has been merged in https://github.com/kubernetes-sigs/controller-runtime/pull/2783

**Pull request closed without merging**
