### PR TITLE
:warning: Bump to kube-1.16.0

### PR DESCRIPTION
**Pull request by enxebre**
Bump to kubernetes-1.16.0 just in case https://github.com/kubernetes-sigs/controller-runtime/pull/588 is not updated

### CODE REVIEW

**Comment by gerred** [comment]
@DirectXMan12 @pwittrock 

@kensipe and I have some cycles to help shepherd and test this and get everything ready to release this update as we need it for KUDO. What would help you most in launching this? Are there other PRs/issues that need to land as well that we can take on?

Thanks! Happy to chat about it in Slack/Zoom/next SIG API Machinery meeting as well.

**Comment by gerred** [comment]
Also what does this mean for generation - does Kubebuilder need to generate out CustomResourceDefinition/v1 instead of v1beta1 after this lands? Is there a delay/compat period for this that's needed?

**Comment by gerred** [comment]
This works and lgtm.

**Comment by enxebre** [comment]
```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go vet ./...
Albertos-MacBook-Pro:controller-runtime@albertogarla $
```

```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go test ./...
ok  	sigs.k8s.io/controller-runtime	(cached) [no tests to run]
?   	sigs.k8s.io/controller-runtime/examples/builtins	[no test files]
?   	sigs.k8s.io/controller-runtime/examples/crd	[no test files]
?   	sigs.k8s.io/controller-runtime/examples/crd/pkg	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/builder	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/cache	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/cache/informertest	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/cache/internal	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/client	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/client/apiutil	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/client/config	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/client/fake	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/controller	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/controller/controllertest	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/controller/controllerutil	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/conversion	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/envtest	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/envtest/printer	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/event	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/handler	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/internal/controller	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/internal/log	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/internal/objectutil	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/internal/recorder	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/leaderelection	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/leaderelection/fake	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/log	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/log/zap	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/manager	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/manager/signals	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/metrics	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/patterns/application	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/patterns/operator	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/predicate	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/reconcile	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/reconcile/reconciletest	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/recorder	(cached) [no tests to run]
?   	sigs.k8s.io/controller-runtime/pkg/runtime	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/runtime/inject	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/runtime/log	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/runtime/scheme	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/runtime/signals	[no test files]
ok  	sigs.k8s.io/controller-runtime/pkg/scheme	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/source	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/source/internal	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/webhook	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/webhook/admission	(cached)
ok  	sigs.k8s.io/controller-runtime/pkg/webhook/conversion	(cached)
?   	sigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher	[no test files]
?   	sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics	[no test files]
```

```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go-apidiff v0.2.2 kube-1.16.0

sigs.k8s.io/controller-runtime/examples/crd/pkg
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *ChaosPod: removed
  - (*ObjectMeta).SetInitializers, method set of *ChaosPod: removed
  - ChaosPod.Initializers: removed
```

```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go-apidiff v0.2.2 kube-1.16.0  --compare-imports

sigs.k8s.io/controller-runtime/examples/crd/pkg
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *ChaosPod: removed
  - (*ObjectMeta).SetInitializers, method set of *ChaosPod: removed
  - ChaosPod.Initializers: removed

k8s.io/api/core/v1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *Event: removed
  - (*ObjectMeta).GetInitializers, method set of *PodTemplateSpec: removed
  - (*ObjectMeta).SetInitializers, method set of *Event: removed
  - (*ObjectMeta).SetInitializers, method set of *PodTemplateSpec: removed
  - Event.Initializers: removed
  - PodTemplateSpec.Initializers: removed

k8s.io/apimachinery/pkg/apis/meta/v1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers: removed
  - (*ObjectMeta).SetInitializers: removed
  - Fields: removed
  - Initializer: removed
  - Initializers: removed
  - ListInterface.GetRemainingItemCount: added
  - ListInterface.SetRemainingItemCount: added
  - ManagedFieldsEntry.Fields: removed
  - Object.GetInitializers: removed
  - Object.SetInitializers: removed
  - ObjectMeta.Initializers: removed

k8s.io/apimachinery/pkg/runtime
  Incompatible changes:
  - Unstructured.NewEmptyInstance: added

k8s.io/apimachinery/pkg/util/sets
  Incompatible changes:
  - String.Delete: changed from func(...string) to func(...string) String
  - String.Insert: changed from func(...string) to func(...string) String

k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *CustomResourceDefinition: removed
  - (*ObjectMeta).SetInitializers, method set of *CustomResourceDefinition: removed
  - CustomResourceDefinition.Initializers: removed
Albertos-MacBook-Pro:controller-runtime@albertogarla $
```

```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go-apidiff master kube-1.16.0

sigs.k8s.io/controller-runtime/examples/crd/pkg
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *ChaosPod: removed
  - (*ObjectMeta).SetInitializers, method set of *ChaosPod: removed
  - ChaosPod.Initializers: removed
Albertos-MacBook-Pro:controller-runtime@albertogarla $
```

```
Albertos-MacBook-Pro:controller-runtime@albertogarla $ go-apidiff master kube-1.16.0 --compare-imports


sigs.k8s.io/controller-runtime/examples/crd/pkg
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *ChaosPod: removed
  - (*ObjectMeta).SetInitializers, method set of *ChaosPod: removed
  - ChaosPod.Initializers: removed

k8s.io/apimachinery/pkg/apis/meta/v1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers: removed
  - (*ObjectMeta).SetInitializers: removed
  - Fields: removed
  - Initializer: removed
  - Initializers: removed
  - ListInterface.GetRemainingItemCount: added
  - ListInterface.SetRemainingItemCount: added
  - ManagedFieldsEntry.Fields: removed
  - Object.GetInitializers: removed
  - Object.SetInitializers: removed
  - ObjectMeta.Initializers: removed

k8s.io/apimachinery/pkg/util/sets
  Incompatible changes:
  - String.Delete: changed from func(...string) to func(...string) String
  - String.Insert: changed from func(...string) to func(...string) String

k8s.io/apimachinery/pkg/runtime
  Incompatible changes:
  - Unstructured.NewEmptyInstance: added

k8s.io/api/core/v1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *Event: removed
  - (*ObjectMeta).GetInitializers, method set of *PodTemplateSpec: removed
  - (*ObjectMeta).SetInitializers, method set of *Event: removed
  - (*ObjectMeta).SetInitializers, method set of *PodTemplateSpec: removed
  - Event.Initializers: removed
  - PodTemplateSpec.Initializers: removed

k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1
  Incompatible changes:
  - (*ObjectMeta).GetInitializers, method set of *CustomResourceDefinition: removed
  - (*ObjectMeta).SetInitializers, method set of *CustomResourceDefinition: removed
  - CustomResourceDefinition.Initializers: removed
Albertos-MacBook-Pro:controller-runtime@albertogarla $
```

**Comment by enxebre** [comment]
@marun @DirectXMan12  rebased and run go-apidiff

**Comment by DirectXMan12** [comment]
cool, looks good.  Holding till we release the 1.15 version (prob later today)

**Comment by DirectXMan12** [comment]
so... technically this is breaking due to a field removal in pkg/envtest/crd.  v0.4.0 it is for this, then

**Comment by DirectXMan12** [comment]
let's maybe do 1.13 as Min Go Version in 0.4.0 as well.

**Comment by DirectXMan12** [comment]
There should already be a 1.13 bump PR around -- #606.  Just listing it out so where aware.  They can merge separately.

The fields removed are the Initializer-related fields.  They show up in ObjectMeta, which shows up in CustomResourceDefinition, which shows up in pkg/envtest.CRDInstallOptions.

**Comment by enxebre** [comment]
@DirectXMan12 rebased

**Comment by njhale** [comment]
This is still being held. It looks like the intent was to cancel the hold earlier (see [comment](https://github.com/kubernetes-sigs/controller-runtime/pull/618#issuecomment-540833515)), but it doesn't seem like `/unhold` did the trick.

**Comment by enxebre** [comment]
yep seems still needs `/hold cancel`  and `/ok-to-test` I don't have perms here
cc @DirectXMan12

**Comment by DirectXMan12** [comment]
whoops lol

/hold cancel
/ok-to-test

/secret-switch-to-enable-prow-to-do-what-I-actually-mean-in-the-future  :-P

**Comment by gerred** [comment]
@kensipe @alenkacz Christmas has come!

**Pull request merged**
