### PR TITLE
✨  Bump k8s.io packages to v1.24.2

### PR DESCRIPTION
**Pull request by FriedrichWilken**
This bumps the patch level of the `k8s.io` packages `api`, `apiextensions-apiserver`, `apimachinery`, `client-go` and `component-base` to `v0.24.2`.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
Great

**Comment by FillZpp** [comment]
/lgtm
Thanks

**Review by camilamacedo86 — APPROVED** [review]
/approved 

Could we do a cherry-pick to the release branch so that it will be in the next patch release?

**Comment by FillZpp** [comment]
PTAL
/cc @alvaroaleman

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
