### PR TITLE
🌱 bump tools kubernetes to v0.27.2

### PR DESCRIPTION
**Pull request by kkkkun**
Bumps tools k8s.io dependencies

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

I think we should not overwrite the indirect dependencies of controller-tools without a good reason.

**Comment by kkkkun** [comment]
> 

 Should we merge https://github.com/kubernetes-sigs/controller-tools/pull/816  firstly and update controller-tools version？

**Comment by sbueringer** [comment]
Not sure if it's worth creating a controller-tools release for. Is there something relevant for controller-tools in 0.27.2?

**Comment by kkkkun** [comment]
> Not sure if it's worth creating a controller-tools release for. Is there something relevant for controller-tools in 0.27.2?

OK.  We should close this.

**Pull request closed without merging**
