### PR TITLE
:sparkles: Rev dependencies to k8s 1.13

### PR DESCRIPTION
**Pull request by detiber**
Updates Kubernetes dependencies to v1.13, required for #275

### CODE REVIEW

**Comment by detiber** [comment]
@vincepri heads up

**Comment by vincepri** [comment]
Also related to #275

**Comment by DirectXMan12** [comment]
To test that this doesn't change the signature of our public interface, I wrote https://github.com/kubernetes-sigs/controller-runtime/pull/229 to help out.  I need to fix it up to get it mergable, but you can run it using the code in the PR in the mean time.  Just generate "before" and "after" outputs, and diff them to make sure things haven't changed.

**Comment by detiber** [comment]
@DirectXMan12 running the external objects tooling returns the following diff:
```sh
diff ~/tmp/cr-external-objects.before ~/tmp/cr-external-objects.after
< "k8s.io/client-go/rest".Config -- struct{Host string; APIPath string; k8s.io/client-go/rest.ContentConfig; Username string; Password string; BearerToken string; Impersonate k8s.io/client-go/rest.ImpersonationConfig; AuthProvider *k8s.io/client-go/tools/clientcmd/api.AuthProviderConfig; AuthConfigPersister k8s.io/client-go/rest.AuthProviderConfigPersister; ExecProvider *k8s.io/client-go/tools/clientcmd/api.ExecConfig; k8s.io/client-go/rest.TLSClientConfig; UserAgent string; Transport net/http.RoundTripper; WrapTransport func(rt net/http.RoundTripper) net/http.RoundTripper; QPS float32; Burst int; RateLimiter k8s.io/client-go/util/flowcontrol.RateLimiter; Timeout time.Duration; Dial func(ctx context.Context, network string, address string) (net.Conn, error)}
---
> "k8s.io/client-go/rest".Config -- struct{Host string; APIPath string; k8s.io/client-go/rest.ContentConfig; Username string; Password string; BearerToken string; BearerTokenFile string; Impersonate k8s.io/client-go/rest.ImpersonationConfig; AuthProvider *k8s.io/client-go/tools/clientcmd/api.AuthProviderConfig; AuthConfigPersister k8s.io/client-go/rest.AuthProviderConfigPersister; ExecProvider *k8s.io/client-go/tools/clientcmd/api.ExecConfig; k8s.io/client-go/rest.TLSClientConfig; UserAgent string; Transport net/http.RoundTripper; WrapTransport func(rt net/http.RoundTripper) net/http.RoundTripper; QPS float32; Burst int; RateLimiter k8s.io/client-go/util/flowcontrol.RateLimiter; Timeout time.Duration; Dial func(ctxcontext.Context, network string, address string) (net.Conn, error)}
```

There is a single (additive) change to the client-go/rest.Config object that adds `BearerTokenFile string` to the object.

**Comment by mengqiy** [comment]
The diff above seems to be fine.

**Comment by DirectXMan12** [comment]
/lgtm
/approve

Thanks for your work!

**Pull request merged**
