### PR TITLE
📖 provide example of client.Patch

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

This PR corrects the example of `client.Create` and provides an example of `client.Patch`

### CODE REVIEW

**Comment by knight42** [comment]
kindly ping @joelanford 😉

**Comment by knight42** [comment]
@alexeldeib Hi! all tests passed now

**Comment by alexeldeib** [comment]
Thanks for adding the example!

/lgtm

**Comment by joelanford** [comment]
Thanks! Looks great.

/approve

**Pull request merged**
