### PR TITLE
🌱 cleanup io/ioutil

### LINKED ISSUE #1518: Fixes for Deprecation of io/ioutil (in Go 1.16)
Please see https://golang.org/doc/go1.16#ioutil

We have a lot of references to ioutil which we need to migrate to newer package(s) mentioned in the url above:
https://cs.k8s.io/?q=io%2Fioutil&i=nope&files=.*%5C.go&excludeFiles=&repos=kubernetes-sigs/controller-runtime

We also need some verify scripts to ensure we don't add back this package

### PR DESCRIPTION
**Pull request by cndoit18**
Signed-off-by: cndoit18 [cndoit18@outlook.com](mailto:cndoit18@outlook.com)
 
**What type of PR is this?**

/kind cleanup
/sig release
 
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1518 
 
**Special notes for your reviewer**:
 
**Does this PR introduce a user-facing change?**:
 
```release-note
It is not very urgent, you can wait until the right time
```

### CODE REVIEW

**Comment by coderanger** [comment]
/hold

Discussion of 1.16 compat issues is in #1518. I'm not sure this PR will help given it's likely to bitrot if we wait many months to require 1.16.

**Comment by FillZpp** [comment]
> Discussion of 1.16 compat issues is in #1518. I'm not sure this PR will help given it's likely to bitrot if we wait many months to require 1.16.

+1
Don't think it's a good idea to make Go 1.16 requirement for all developers.

**Comment by palnabarun** [comment]
Note: The changes in this PR will be more relevant when we make Go 1.16+ mandatory for users of this library.

/remove-sig release
/sig api-machinery architecture
/area code-organization

**Pull request closed without merging**
