### PR TITLE
:sparkles: Allow setting "UseExistingCluster" via environment

### PR DESCRIPTION
**Pull request by ichekrygin**
This PR is an attempt to address feature request: #222 
Non-breaking feature: sparkles (:sparkles:)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
/kind feature

Can you please tag the PR title according to https://github.com/kubernetes-sigs/controller-runtime/blob/master/VERSIONING.md#pr-process ?  Thanks!

**Comment by DirectXMan12** [comment]
We tend to try and favor using structs directly with sane defaults instead of constructors, when possible.  Can you make this work with the existing setup?  If you need to make a breaking change, now would be the time to do it ;-)

**Comment by ichekrygin** [comment]
@DirectXMan12 thank you for looking into this. 

I think I share the sentiment of using structs directly with sane defaults. In this case, however, the struct `Environment` already has a field `UseExistingCluster` which I am attempting to set on "client/user" behalf, hence the "constructor" implementation. 
The motivation is(was) not to "leak" environment variable value testing into the "client" code.

The alternative, "constructor-less" solution may look a bit ugly and convoluted (or maybe not): 

in `server.go`
```go
func UseExistingCluster() bool {
	return strings.ToLower(os.Getenv(envUseExistingCluster)) == "true"
}
```

in client code:

``` go
func TestMain(m *testing.M) {
	t := &envtest.Environment{
		CRDDirectoryPaths: []string{filepath.Join("..", "..", "..", "..", "..", "config", "crds")},
                UseExistingCluster: envtest.UseExistingCluster(),
	}
...
```

@DirectXMan12 would you be open to "contsturctor" like solion? If so - I will update the PR with...
I guess: "Non-breaking feature: sparkles (:sparkles:)" - is it?

**Comment by DirectXMan12** [comment]
So, the other option is changing `UseExistingCluster bool` to `UseExistingCluster *bool`, since most people probably don't want to set `UseExistingCluster` anyway, the awkwardness of builtin-pointers isn't super onerous.  Sometimes I miss being able to write `Option<bool>`...

**Comment by ichekrygin** [comment]
I think I am coming to a realization that this is best handled in each individual project, rather than being built in. Closing.

**Pull request closed without merging**
