### PR TITLE
:seedling: Add Dependabot for dependency management

### PR DESCRIPTION
**Pull request by kannon92**
In the slack channel for controller-runtime, it was suggested to add dependabot to controller-runtime.  This PR adds dependabot for go and github actions.  

I am unfamilar with this repo so please let me know if there is any other items that should be included.

### CODE REVIEW

**Review by camilamacedo86 — APPROVED** [review]
/lgtm

**Comment by camilamacedo86** [comment]
moving forward with this one since it is just for us to begin to be able to get the deps automatically.

**Comment by alvaroaleman** [comment]
@camilamacedo86 would you mind not approving things in a repo you are not an approver in? The thing is creating a bunch of PRs that are explicitly wrong, like bumping k8s.io/ packages to v0.27: https://github.com/kubernetes-sigs/controller-runtime/pull/2064

**Pull request merged**
