### PR TITLE
Prepare for v0.5.7

### PR DESCRIPTION
**Pull request by vincepri**
This PR backports some fixes and updates from the current release to release-0.5.

### CODE REVIEW

**Comment by vincepri** [comment]
@JoelSpeed This backports the log line fix we discussed last week

**Comment by detiber** [comment]
/lgtm
/hold
hold to allow for @alvaroaleman a chance to take a look

**Comment by alvaroaleman** [comment]
Thanks!
/lgtm
/hold cancel

Sidenote, right now there is a set of features/bugfixes that only exist in a 0.5.X release but not in a 0.6.X release, I think we should do a release of the latter as well so ppl dont lose fixes by upgrading :grimacing:

**Pull request merged**
