### PR TITLE
✨ Update dependencies to Kubernetes v1.16.4

### PR DESCRIPTION
**Pull request by ialidzhikov**
Bump dependencies for Kubernetes 1.16.4.

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I suspect this cherry-pick to 1.16.1 - https://github.com/kubernetes/kubernetes/pull/82618. 
`PollUntil` is replaced with `PollImmediateUntil` and looks like the cache_test is relying on this 100 millis sleep. If add it before each `WaitForCacheSync` invocation the tests pass. 😕 

/help

**Comment by gerred** [comment]
@ialidzhikov will you fix the merge conflicts here? thank you!

**Comment by gerred** [comment]
@ialidzhikov would you fix the merge conflict here and I will kick off a retest?

Also, would it make sense to instead go to 1.17.1 here?

**Comment by vincepri** [comment]
Not sure when the next controller-runtime release is, but I'd consider updating and releasing for 1.16 first, the updated kubebuilder tools just landed a few weeks ago, so we should be good for testing

**Comment by vincepri** [comment]
/retitle ✨ Update dependencies to Kubernetes v1.16.4

**Comment by vincepri** [comment]
@ialidzhikov Are you able to rebase?

**Comment by gerred** [comment]
@vincepri :+1: that sgtm, then we'll work toward a 1.17 deps version. I definitely want to get _better_ about having more timely dependency updates with Kubernetes releases (maybe in a pre-release setting). I think we could build some automation a la dependabot to potentially help us here so it's not a massive, manual resolution every time we go to do this.

**Comment by ialidzhikov** [comment]
I will rebase later today but as I described there is a test https://github.com/kubernetes-sigs/controller-runtime/pull/732#issuecomment-566703487 failure. I will need to check whether the test needs to be adapted or something else.
Feel free to propose a new PR about it if you have the resolution and the tests passing.

@munnerz, what was your proposal here? To do the `time.Sleep` patch as in https://github.com/jetstack/cert-manager/pull/2290/commits/fdce8c640620e61be9af143983ef45278004084f ?

**Comment by vincepri** [comment]
@ialidzhikov Unfortunately I can't see the test failure because of the rebase, but as soon as that's done, I can take a look!

**Comment by ialidzhikov** [comment]
Ha, the tests now passed. Looks like the failing test was fixed with kubernetes-sigs/controller-runtime#755.

**Comment by ialidzhikov** [comment]
Ha, the tests now passed. Looks like the failing test was fixed with kubernetes-sigs/controller-runtime#755.

**Comment by ialidzhikov** [comment]
ping @gerred @DirectXMan12

**Comment by vincepri** [comment]
@ialidzhikov Given that https://github.com/kubernetes-sigs/controller-runtime/pull/754 is already in the milestone and based on a newer version, would it be ok to close this PR in favor of that one?

**Comment by ialidzhikov** [comment]
> @ialidzhikov Given that #754 is already in the milestone and based on a newer version, would it be ok to close this PR in favor of that one?

If the next minor release is planned to be a breaking one, then I am fine to close this PR.

**Comment by gerred** [comment]
@DirectXMan12 what's your feelings here? I was going to get this PR in in the thoughts we were going to cut a 1.16.x release.

**Comment by DirectXMan12** [comment]
If folks are super-interested, we can probably re-target this to a stable branch.  Otherwise, due to timing, I think it prob makes sense just to go for 1.17 for the next release.

**Comment by ialidzhikov** [comment]
Closing in favour of #789 or #754.

**Pull request closed without merging**
