### PR TITLE
🌱 Bump to Kubernetes v0.28.0-beta.0

### PR DESCRIPTION
**Pull request by sbueringer**
Bumps to latest Kubernetes 1.28.

I think we don't necessary have to bump to every alpha / beta. So we can keep this around a bit and continue bumping & testing newer Kubernetes versions.

/hold

### CODE REVIEW

**Comment by sbueringer** [comment]
Bumped to beta.0  I would suggest to merge it 

/hold cancel

**Review by alvaroaleman — APPROVED** [review]

**Comment by alvaroaleman** [comment]
Buml

**Pull request merged**
