### PR TITLE
🐛 Fake client should set resource version on init objects

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
This might be a breaking change for some ppl :grimacing:

**Comment by vincepri** [comment]
Even if it only gets set in case it's empty?

**Comment by vincepri** [comment]
Oh well, it seems it is indeed a breaking change. I can't blame @DirectXMan12 for wanting to deprecate the fake client as-is

**Comment by DirectXMan12** [comment]
hmm... I *think* this should be non-breaking -- the real apiserver sets this, and explicitly guarantees it to not be anything in particular beyond "monotonically increasing on any given object between changes".

@alvaroaleman what was your reasoning behind it being breaking -- does my reasoning above seem sound?

**Comment by alvaroaleman** [comment]
> @alvaroaleman what was your reasoning behind it being breaking -- does my reasoning above seem sound?

Its sound wrt to what the apiserver does, but there are lots of tests out there that create some objects in the fakeclient, then retrieve them and do a `DeepEqual` with a reference. All of them will break after this change :upside_down_face:

**Comment by vincepri** [comment]
I was thinking to make a deep copy and store that one with the resource version, so you could get it after. 

I’ve also noticed that patch doesn’t change resource version if there are changes, but that’s a different problem / PR

**Comment by vincepri** [comment]
Closing this for now, if anyone would like to do this change definitely welcome to

/close

**Pull request closed without merging**
