### PR TITLE
✨  Support multiple field selectors

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Review by FillZpp — COMMENTED** [review]
Emm.. I don't think we can support this by listing objects multiple times. You have to know that the indexer always keep changing, which means the objects might be modified between the multiple lists.

For example, when user list with field selectors `{"field1": "a", "field2": "b"}`, he/she wants to get objects that match the two requirements. But there may be an object that previously have `{"field1": "a", "field2": "y"}` so it is returned by your first list with `field1` index. And then someone updates it to be `{"field1": "x", "field2": "b"}`, so it is also returned by your second list with `field2` index.

In this way, you will return the object to user, but the problem is that it has never matched the two requirements at the same time.

**Comment by tamalsaha** [comment]
Makes sense, @FillZpp !

**Comment by tamalsaha** [comment]
Thanks @FillZpp ! I have added checks for generation. Now, we can be sure that the result for the all indices are for the same object.

**Comment by weilaaa** [comment]
Hi, there. I wanna add a complicated index into thread safe store. If it will be accepted, it helps here.

Related [issues](https://github.com/kubernetes/kubernetes/issues/109329#issuecomment-1107688739) and [pr](https://github.com/kubernetes/kubernetes/pull/109334)

**Comment by vincepri** [comment]
Closing due to inactivity, @tamalsaha please feel free to reopen once ready

/close

**Pull request closed without merging**
