### PR TITLE
Add options to client.Delete()

### LINKED ISSUE #76: client.Delete doesn't support PropagationPolicy and other delete options
The controller-runtime client doesn't seem to support passing `DeleteOptions` in the body of a delete request.

Use case: when a [Job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) is deleted, its pods are normally orphaned by the GC. To delete a Job and GC its pods with the normal client-go, I pass a `DeleteOptions` with `PropagationPolicy` set. I can't do that with the controller-runtime client.

### PR DESCRIPTION
**Pull request by grantr**
Allows Delete requests to carry options like GracePeriodSeconds, Preconditions, and PropagationPolicy. I chose the functional options pattern here so the function signature remains the same for all existing callsites.

To use the default options, call Delete with the same signature as before:

```go
client.Delete(context.TODO(), obj)
```

This Delete call sets a GracePeriodSeconds for the request:

```go
client.Delete(context.TODO(), obj, client.GracePeriodSeconds(1))
```

Multiple options can be set:

```go
client.Delete(context.TODO(), obj,
  client.GracePeriodSeconds(1),
  client.PropagationPolicy(metav1.DeletePropagationForeground))
```

I wrote tests for the DeleteOptions struct, but I wasn't sure how to test the actual request content. With the current testing strategy, we can only test behavior by inspecting what the apiserver did, and in this case that's fairly subtle since it involves timeouts and cascading deletes. It would be easier to use `httptest` or a similar mock to inspect the request that's sent by the client.

Fixes #76.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Our list options are chained instead of varargs.  I'm not necessary objecting to the varargs approach (I like how it ends up looking, but I think there are merits to both), but I think we need to be consistent.

**Comment by grantr** [comment]
In general, the benefit of functional options is that they're invisible until you need them. This seems more useful for `Delete` than `List`. I expect `Delete` options will be rarely used, while almost all `List` calls will use options. The two operations have different ergonomic needs.

I can create another PR exploring functional `ListOptions` if that seems useful.

**Comment by DirectXMan12** [comment]
> In general, the benefit of functional options is that they're invisible until you need them.

Agreed, I do like that aspect.

> I can create another PR

yeah, I think we should have a common experience.  Please do create a separate PR for varargs list options.

**Comment by droot** [comment]
@grantr will wait for your second PR to compare how it looks.

Also, another major factor to consider is that the changes should be backward compatible. Implementation in current PR meets that criterion.

**Comment by grantr** [comment]
> I would rewrite the tests to capture desired behavior from a user perspective though, instead of being broken out into the smallest possible units.

The list you propose is all the existing tests less one! 😜I folded the `metav1.DeleteOptions` test into the others and refactored a bit. Take a look, let me know what you think.

**Comment by DirectXMan12** [comment]
tests look good.  will do one more pass tonight or tomorrow morning, then merge.

**Comment by DirectXMan12** [comment]
whoops, looks like you missed a fake implementation in one of the tests.

**Comment by DirectXMan12** [comment]
Still *technically* a incompatible change then, I think.  We'll do it once everything's migrated to the pinned deps.

**Comment by grantr** [comment]
Can this change also go forward with https://github.com/kubernetes-sigs/controller-runtime/pull/106#issuecomment-418516452?

**Comment by DirectXMan12** [comment]
Yep, this can go forward now.

**Comment by DirectXMan12** [comment]
Fix golint issues (some missing godocs), and this is good to go.

**Comment by grantr** [comment]
Fixed the golint issues and rebased into a single commit.

**Comment by grantr** [comment]
Looks like the gosec check is failing, but it doesn't seem to be anything related to the changes in this PR.

**Comment by grantr** [comment]
All good now.

**Pull request merged**
