### PR TITLE
Bump to Kubernetes 1.19-rc.3

### PR DESCRIPTION
**Pull request by joelanford**
This PR bumps controller-runtime dependencies to Kubernetes 1.19.

Note that Kubernetes 1.19 is not GA yet. This PR will be updated when it is GA.

/hold

### CODE REVIEW

**Comment by rifelpet** [comment]
Hi @joelanford, is there any chance this could get merged sooner than 1.19.0 stable being released? Theres a breaking change in `github.com/go-logr/logr v0.2.0` that is making it difficult for users to upgrade their kubernetes dependencies to the 1.19 prereleases without controller-runtime also having logr updated to 0.2.0.

Merging this would allow us (Kops) to bump our controller-runtime dependency to the latest master commit and update all kubernetes dependencies to the latest 1.19 RC. This allows us to get CI signal with 1.19 without having to wait for 1.19.0 stable to be released. When it is released we could update controller-runtime's dependencies once more and follow the normal release process. 

For more info see https://github.com/go-logr/logr/pull/20 (and the linked issue) and the build failure [here](https://github.com/kubernetes/kops/pull/9565/checks?check_run_id=926018178).

**Comment by joelanford** [comment]
> is there any chance this could get merged sooner than 1.19.0 stable being released?

@rifelpet there was discussion at yesterday's kubebuilder/controller-runtime/controller-tools community meeting about doing exactly this.

The decision was that we could merge this PR prior to GA, but then not cut the release for v0.7.0 until we update to the GA deps.

I think we decided to make another few non-breaking changes on `master` so that we can cut another `v0.6.x` release to avoid some backports.

I'll update this PR again to the latest 1.19 deps.

/cc @vincepri @DirectXMan12

**Comment by alvaroaleman** [comment]
Can we use a go-logr version that has https://github.com/go-logr/logr/pull/20 ?

**Comment by vincepri** [comment]
Removing the ⚠️, given that I expect we update to 1.19.0/1 and that should go in the actual release notes

**Pull request merged**
