### PR TITLE
🐛 Don't error if the CRD is already present

### PR DESCRIPTION
**Pull request by coderanger**
Ignores this one error for cases with UseExistingServer because if using the same control plane for multiple suites, the CRDs will already be loaded in after the first.

A possible tweak would be to do a full create-or-update instead but it seems unlikely to matter.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Should this just be createorupdate?  If it already exists you probably want to make sure it's up-to-date

**Comment by coderanger** [comment]
@DirectXMan12 CreateOrUpdate removes some class of tests around upgrades. I would generally say that if they are already present, it means you probably set them up on purpose :)

**Comment by DirectXMan12** [comment]
ah, hmm... perhaps we should at least log?

**Comment by lukaszo** [comment]
@codenrhoden any update here? I would love to have it merged

**Comment by codenrhoden** [comment]
@lukaszo looks like you were trying to ping @coderanger instead. =)

**Comment by lukaszo** [comment]
@codenrhoden ups, sorry for pinging :)

**Comment by pires** [comment]
I think it should be `CreateOrUpdate`, just in the case you have changed your CRDs in between runs.

**Pull request closed without merging**
