### PR TITLE
🐛 fix List method for metadataClient

### PR DESCRIPTION
**Pull request by Iceber**
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>

I think the `List` method should not modify the `GVK` of the `obj`

### CODE REVIEW

**Review by alvaroaleman — COMMENTED** [review]
@Iceber Could you please add a testcase for this?

/ok-to-test

**Comment by vincepri** [comment]
+1 for a test case

**Comment by Iceber** [comment]
@alvaroaleman @vincepri I observed that it is common in `controller-runtime` to write BDD tests for exportable methods or structures, is it necessary to add a separate test for `metadataClient` as a non-exportable structure?

The bug in the List method of `metadataClient` is circumvented by reset in `(*client) List`.
https://github.com/kubernetes-sigs/controller-runtime/blob/9fe547c87bf12c6c0177eb830fcc85cf083231de/pkg/client/client.go#L258-L270
Here is the fix for the obvious problem with `(*metadataClient).List`.

**Comment by vincepri** [comment]
@Iceber You could probably add a new test file in the same package to test the internals only

**Comment by Iceber** [comment]
> @Iceber You could probably add a new test file in the same package to test the internals only

Okay, I'll do it. 😀

**Comment by vincepri** [comment]
@Iceber Any updates for a simple test case?

**Comment by vincepri** [comment]
@Iceber do you still have time to tackle this?

**Comment by Iceber** [comment]
@vincepri Sorry for the long delay in adding the test.

**Pull request closed without merging**
