### PR TITLE
🏃 Bump go.mod to use versions instead of SHAs.

### PR DESCRIPTION
**Pull request by armandgrillet**
We use SHAs to specify versions of our dependencies, e.g. `k8s.io/utils v0.0.0-20190801114015-581e00157fb1`. Instead, where possible, I have replaced the SHAs with the latest version using the same major version (in our case, `v0.16.6`). The intent is to make the `go.mod` more readable/upgradable.

### CODE REVIEW

**Comment by gerred** [comment]
Holding this until we decide what to do with #754 and #732

**Comment by vincepri** [comment]
Closing this now that #795 has merged

/close

**Pull request closed without merging**
