### PR TITLE
:warning: Update go-logr/logr v0.1.0 -> v0.2.0

### PR DESCRIPTION
**Pull request by micnncim**
## What

[go-logr](https://github.com/go-logr/logr) has been updated to `v0.2.0`, including incompatible change, so we cannot use both `go-logr` `v0.2.0` and `controller-runtime` `v0.6.0` simultaneously.

This PR updates `go-logr` version so that we can use `controller-runtime` with `go-logr` `v0.2.0`.

### CODE REVIEW

**Comment by micnncim** [comment]
@gerred What do you think about this?

**Comment by vincepri** [comment]
Probably need to wait for the next breaking release

**Comment by justenwalker** [comment]
If this upstream patch gets merged, upgrading to 0.2.1 might make this change non-breaking 

https://github.com/go-logr/logr/pull/20

**Comment by micnncim** [comment]
dup: https://github.com/kubernetes-sigs/controller-runtime/pull/1011

**Pull request closed without merging**
