### PR TITLE
🌱 Bump k8s.io deps to v0.26.0

### LINKED ISSUE #2035: Bump k8s to 1.26
Creating an issue to ask for the 1.26 bump. https://www.k8s.dev/resources/release/#kubernetes-126

K8S 1.26 GA date is 2002/12/06

### PR DESCRIPTION
**Pull request by lucacome**
Signed-off-by: Luca Comellini <luca.com@gmail.com>

Updates k8s.io dependencies to stable `v0.26.0`

Closes #2035

### CODE REVIEW

**Comment by vincepri** [comment]
@lucacome seems some linter issues to fix

**Comment by lucacome** [comment]
@vincepri I've fixed them

**Review by vincepri — APPROVED** [review]
/lgtm

**Pull request merged**
