### PR TITLE
:bug: Serve metrics even if not leader

### LINKED ISSUE #196: Serve metrics for non-leader pods
When using leader election, metrics aren't served and so the non-leader pods are shown as "Down" by prometheus when it scrapes the pod.

Raised originally in https://github.com/kubernetes-sigs/controller-runtime/pull/132#issuecomment-435051399

To fix this, controller-runtime should start serving metrics while waiting to acquire leader status.
We need to make sure however that it doesn't serve metrics that are false, prometheus should pick up no time series from it and just connect, read and get a basically empty document.

### PR DESCRIPTION
**Pull request by JoelSpeed**
Fixes #196.

Move metrics serving to before we separate into the leader election vs non leader election start process.

This allows prometheus to count non-leader targets as up, but will just receive an empty response for non-leaders and so no inaccurate metrics are collected.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
I think this LGTM.

Looks like the test issue is in the metrics test: https://travis-ci.org/kubernetes-sigs/controller-runtime/jobs/450256058#L617

**Comment by DirectXMan12** [comment]
Looks like it's affecting multiple PRs (e.g. #193).  I'd guess it's a flake.  I'm going to fork off a separate bug.

**Comment by JoelSpeed** [comment]
@DirectXMan12 I've rebased this now #200 is merged, tests are passing now

**Comment by DirectXMan12** [comment]
looks like there's a merge conflict.  rebase and we'll get this merged.

**Comment by JoelSpeed** [comment]
@DirectXMan12 Rebased, should be good to go now

**Pull request merged**
