### PR TITLE
🏃 don't use apidiff on dirty commits

### PR DESCRIPTION
**Pull request by alexeldeib**
ref https://github.com/kubernetes-sigs/controller-runtime/pull/909#issuecomment-615505119

### CODE REVIEW

**Comment by vincepri** [comment]
Is this because it's running during `make test`?

**Comment by alexeldeib** [comment]
Yeah, exactly. I didn’t double check if it was the apidiff binary itself making the tree dirty or something else, but I figure this is fine either way.

**Comment by alexeldeib** [comment]
I thought it might be because of make test, but they're in separate containers on prow so that can't be it. My other two thoughts are either it's because the binary is built under the git path which makes it dirty or it's something due to how prow checks it out (I looked at that code and nothing stood out immediately).

Either way, I figure we can add logging and try to force it through. We can at least ensure it's running against the right commits and figure out why it fails in the future.

**Comment by alexeldeib** [comment]
Would've helped to test on the right branch -_- was wondering why prow wasn't retesting for me


The issue was with go.sum. I guess go changed a crypto library out under us? I left the `git status` in case this happens again. We can always revisit and clean up this script further.

**Comment by alexeldeib** [comment]
fixes #681

**Comment by joelanford** [comment]
@alexeldeib @vincepri FYI, not sure this is related, but I have noticed some cases where go-apidiff will leave the git tree in a dirty state when it is finished. I haven't had the time to dig into why that happens, but if you notice that, let me know and we can dig deeper.

**Pull request merged**
